language: perl
perl:
  - "5.16"
env:
  - PERL_CPANM_OPT="-v --mirror http://cpan.mirrors.travis-ci.org  --mirror http://cpan.cpantesters.org/ --mirror http://search.cpan.org/CPAN --cascade-search --notest --force --skip-satisfied --no-interactive"
before_install:
  - cpanm -n Module::Install Catalyst::Devel
  - cd web
notifications:
  irc:
    channels:
      - "irc.perl.org#sao-paulo.pm"