package SPPM::Web::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'SPPM::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=sppm_dev;host=localhost',
        user => 'postgres',
        password => 'system',
        quote_names => q{1},
    }
);

=head1 NAME

SPPM::Web::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<SPPM::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<SPPM::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

renato

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
